import "./globals.css";
import { Poppins } from "next/font/google"
import Mouse from "@/components/Mouse";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
})

export const metadata = {
  title: "Color Wars",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased h-screen`}
      >
        {children}
        <Mouse/>
      </body>
    </html>
  );
}
